version: '3'

services:
  datascience:
    build: .
    ports:
      - "8888:8888" # jupyter lab
      - "5555:5000" # mlflow ui
      - "4141:4141" # kedro viz
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/code
    user: root
    container_name: budoka-container
    tty: true
    stdin_open: true

